spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskmanagerdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.mail.from=${MAIL_FROM:no-reply@taskmanager.local}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
